export const ALL_CHARACTERS: string[] = [
  'Homer Simpson',
  'Marge Simpson',
  'Bart Simpson',
  'Lisa Simpson',
  'Maggie Simpson',
  'Abraham Simpson',
  "Santa's Little Helper",
  'Snowball II',
  'Snowball V',
  'Apu Nahasapeemapetilon',
  'Barney Gumble',
  'Bleeding Gums Murphy',
  'Chief Clancy Wiggum',
  'Dewey Largo',
  'Eddie',
  'Edna Krabappel',
  'Itchy & Scratchy',
  'Janey Powell',
  'Jasper Beardly	',
  'Jimbo Jones',
  'Kearney Zzyzwicz',
  'Kent Brockman',
  'Krusty the Clown',
  'Lenny Leonard',
  'Lionel Hutz',
  'Luann Van Houten',
  'Martin Prince',
  'Maude Flanders',
  'Milhouse Van Houten',
  'Miss Hoover',
  'Moe Szyslak',
  'Ned Flanders',
  'Nelson Muntz',
  'Otto Mann',
  'Patty Bouvier',
  'Principal Skinner',
  'Professor Frink',
  'Rainier Wolfcastle',
  'Ralph Wiggum',
  'Rod Flanders',
  'Seymour Skinner',
  'Sherri & Terri',
  'Sideshow Bob',
  'Sideshow Mel',
  'Snake Jailbird',
  'Troy McClure',
  'Waylon Smithers',
  'Wendell Borton',
  'Abe Simpson',
  'Agnes Skinner',
  'Allison Taylor',
  'Aristotle Amadopolis',
  'Artie Ziff',
  'Bernice Hibbert',
  'Birch Barlow',
  'Brandine Spuckler',
  'Reverend Timothy Lovejoy',
  'C. Montgomery Burns',
  'Carl Carlson',
  'Cletus Spuckler',
  'Comic Book Guy',
  'Cookie Kwan',
  'Disco Stu',
  'Dr. Hibbert',
  'Dr. Nick Riviera',
  'Duffman',
  'Eleanor Abernathy',
  'Elizabeth Hoover',
  'Fat Tony',
  'Frank Grimes',
  'Gil Gunderson',
  'Groundskeeper Willie',
  'Hans Moleman',
  'Helen Lovejoy',
  'Herman Hermann',
  'Hollis Hurlbut',
  'Jacqueline Bouvier',
  'Jebediah Springfield',
  'Judge Roy Snyder',
  'Kang & Kodos',
  'Kirk Van Houten',
  'Lionel Hutz',
  'Lunchlady Doris',
  'Mayor Quimby'
]

export const THE_SIMPSONS_FAMILY: string[] = [
  'Homer Simpson',
  'Marge Simpson',
  'Bart Simpson',
  'Lisa Simpson',
  'Maggie Simpson',
  'Abe Simpson',
  "Santa's Little Helper",
  'Snowball II',
  'Snowball V'
]
