import { Character } from '../types'

const slugify = (s: string) =>
  s
    .trim()
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

export const ALL_CHARACTERS: Character[] = [
  { id: slugify('Homer Simpson'), name: 'Homer Simpson', aliases: ['Homer'], isSimpson: true },
  { id: slugify('Marge Simpson'), name: 'Marge Simpson', aliases: ['Marge'], isSimpson: true },
  { id: slugify('Bart Simpson'), name: 'Bart Simpson', aliases: ['Bart'], isSimpson: true },
  { id: slugify('Lisa Simpson'), name: 'Lisa Simpson', aliases: ['Lisa'], isSimpson: true },
  { id: slugify('Maggie Simpson'), name: 'Maggie Simpson', aliases: ['Maggie'], isSimpson: true },
  { id: slugify('Abraham Simpson'), name: 'Abraham Simpson', aliases: ['Abe Simpson'], isSimpson: true },
  { id: slugify("Santa's Little Helper"), name: "Santa's Little Helper", isSimpson: true },
  { id: slugify('Snowball II'), name: 'Snowball II', aliases: ['Snowball', 'Snowball 2'], isSimpson: true },
  { id: slugify('Snowball V'), name: 'Snowball V', aliases: ['Snowball 5'], isSimpson: true },
  { id: slugify('Apu Nahasapeemapetilon'), name: 'Apu Nahasapeemapetilon', aliases: ['Apu'] },
  { id: slugify('Barney Gumble'), name: 'Barney Gumble', aliases: ['Barney'] },
  { id: slugify('Bleeding Gums Murphy'), name: 'Bleeding Gums Murphy' },
  { id: slugify('Chief Clancy Wiggum'), name: 'Chief Clancy Wiggum', aliases: ['Clancy Wiggum', 'Chief Wiggum'] },
  { id: slugify('Dewey Largo'), name: 'Dewey Largo' },
  { id: slugify('Eddie'), name: 'Eddie' },
  { id: slugify('Edna Krabappel'), name: 'Edna Krabappel' },
  { id: slugify('Itchy & Scratchy'), name: 'Itchy & Scratchy', aliases: ['Itchy and Scratchy'] },
  { id: slugify('Janey Powell'), name: 'Janey Powell' },
  { id: slugify('Jasper Beardly'), name: 'Jasper Beardly' },
  { id: slugify('Jimbo Jones'), name: 'Jimbo Jones', aliases: ['Jimbo'] },
  { id: slugify('Kearney Zzyzwicz'), name: 'Kearney Zzyzwicz' },
  { id: slugify('Kent Brockman'), name: 'Kent Brockman' },
  { id: slugify('Krusty the Clown'), name: 'Krusty the Clown', aliases: ['Krusty'] },
  { id: slugify('Lenny Leonard'), name: 'Lenny Leonard', aliases: ['Lenny'] },
  { id: slugify('Lionel Hutz'), name: 'Lionel Hutz' },
  { id: slugify('Luann Van Houten'), name: 'Luann Van Houten' },
  { id: slugify('Martin Prince'), name: 'Martin Prince' },
  { id: slugify('Maude Flanders'), name: 'Maude Flanders' },
  { id: slugify('Milhouse Van Houten'), name: 'Milhouse Van Houten', aliases: ['Milhouse'] },
  { id: slugify('Moe Szyslak'), name: 'Moe Szyslak', aliases: ['Moe'] },
  { id: slugify('Ned Flanders'), name: 'Ned Flanders' },
  { id: slugify('Nelson Muntz'), name: 'Nelson Muntz', aliases: ['Nelson'] },
  { id: slugify('Otto Mann'), name: 'Otto Mann', aliases: ['Otto'] },
  { id: slugify('Patty Bouvier'), name: 'Patty Bouvier' },
  { id: slugify('Professor Frink'), name: 'Professor Frink' },
  { id: slugify('Rainier Wolfcastle'), name: 'Rainier Wolfcastle' },
  { id: slugify('Ralph Wiggum'), name: 'Ralph Wiggum' },
  { id: slugify('Rod Flanders'), name: 'Rod Flanders' },
  { id: slugify('Seymour Skinner'), name: 'Seymour Skinner', aliases: ['Principal Skinner'] },
  { id: slugify('Sherri & Terri'), name: 'Sherri & Terri', aliases: ['Sherri and Terri'] },
  { id: slugify('Sideshow Bob'), name: 'Sideshow Bob' },
  { id: slugify('Sideshow Mel'), name: 'Sideshow Mel' },
  { id: slugify('Snake Jailbird'), name: 'Snake Jailbird', aliases: ['Snake'] },
  { id: slugify('Troy McClure'), name: 'Troy McClure' },
  { id: slugify('Waylon Smithers'), name: 'Waylon Smithers', aliases: ['Smithers'] },
  { id: slugify('Wendell Borton'), name: 'Wendell Borton' },
  { id: slugify('Agnes Skinner'), name: 'Agnes Skinner' },
  { id: slugify('Allison Taylor'), name: 'Allison Taylor' },
  { id: slugify('Aristotle Amadopolis'), name: 'Aristotle Amadopolis' },
  { id: slugify('Artie Ziff'), name: 'Artie Ziff' },
  { id: slugify('Bernice Hibbert'), name: 'Bernice Hibbert' },
  { id: slugify('Birch Barlow'), name: 'Birch Barlow' },
  { id: slugify('Brandine Spuckler'), name: 'Brandine Spuckler' },
  { id: slugify('Reverend Timothy Lovejoy'), name: 'Reverend Timothy Lovejoy', aliases: ['Reverend Lovejoy', 'Timothy Lovejoy', 'Rev. Lovejoy'] },
  { id: slugify('C. Montgomery Burns'), name: 'C. Montgomery Burns', aliases: ['Montgomery Burns', 'Mr. Burns', 'Charles Montgomery Burns'] },
  { id: slugify('Carl Carlson'), name: 'Carl Carlson' },
  { id: slugify('Cletus Spuckler'), name: 'Cletus Spuckler', aliases: ['Cletus'] },
  { id: slugify('Comic Book Guy'), name: 'Comic Book Guy', aliases: ['Jeff Albertson'] },
  { id: slugify('Cookie Kwan'), name: 'Cookie Kwan' },
  { id: slugify('Disco Stu'), name: 'Disco Stu' },
  { id: slugify('Dr. Hibbert'), name: 'Dr. Hibbert', aliases: ['Julius Hibbert'] },
  { id: slugify('Dr. Nick Riviera'), name: 'Dr. Nick Riviera', aliases: ['Dr. Nick'] },
  { id: slugify('Duffman'), name: 'Duffman' },
  { id: slugify('Eleanor Abernathy'), name: 'Eleanor Abernathy', aliases: ['Crazy Cat Lady'] },
  { id: slugify('Elizabeth Hoover'), name: 'Elizabeth Hoover', aliases: ['Miss Hoover'] },
  { id: slugify('Fat Tony'), name: 'Fat Tony', aliases: ["Anthony D'Amico"] },
  { id: slugify('Frank Grimes'), name: 'Frank Grimes' },
  { id: slugify('Gil Gunderson'), name: 'Gil Gunderson' },
  { id: slugify('Groundskeeper Willie'), name: 'Groundskeeper Willie', aliases: ['Willie'] },
  { id: slugify('Hans Moleman'), name: 'Hans Moleman' },
  { id: slugify('Helen Lovejoy'), name: 'Helen Lovejoy' },
  { id: slugify('Herman Hermann'), name: 'Herman Hermann', aliases: ['Herman'] },
  { id: slugify('Hollis Hurlbut'), name: 'Hollis Hurlbut' },
  { id: slugify('Jacqueline Bouvier'), name: 'Jacqueline Bouvier' },
  { id: slugify('Jebediah Springfield'), name: 'Jebediah Springfield' },
  { id: slugify('Judge Roy Snyder'), name: 'Judge Roy Snyder' },
  { id: slugify('Kang & Kodos'), name: 'Kang & Kodos', aliases: ['Kang and Kodos'] },
  { id: slugify('Kirk Van Houten'), name: 'Kirk Van Houten' },
  { id: slugify('Lunchlady Doris'), name: 'Lunchlady Doris', aliases: ['Doris'] },
  { id: slugify('Mayor Quimby'), name: 'Mayor Quimby', aliases: ['Joe Quimby'] }
]
